### ISSUE TITLE
Support for scheduled events?

### ISSUE THREAD

**Issue by nason** [eltimn/slugify-action#23]
Thanks for the great action! I have a workflow that is triggered by pushes to main, pull requests, _and_ on a nightly schedule. This action is failing the scheduled workflow runs with

>Run eltimn/slugify-action@v2.0.1
>Error: No implementation for event_name: schedule

It looks like [`schedule` events](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule) include the necessary sha and ref. Any objection to adding support?

**Comment by eltimn** [comment]
I'll look into it.

**Comment by eltimn** [comment]
I just released v2.0.2 which allows for use in a scheduled workflow.
